### PR TITLE
Fix an issue with not finding the go_asm.h header file generated from go tool compile 

### LINKED ISSUE #115: Problems compiling github.com/pierrec/lz4/v4 with `go_repo`
```
///third_party/go/github.com_pierrec_lz4_v4//internal/lz4block:_lz4block#asm
Error building target ///third_party/go/github.com_pierrec_lz4_v4//internal/lz4block:_lz4block#asm: exit status 1
pkg/linux_amd64/github.com/pierrec/lz4/v4/internal/lz4block/decode_amd64.s, line 122: expected pseudo-register; found DI
pkg/linux_amd64/github.com/pierrec/lz4/v4/internal/lz4block/decode_amd64.s, line 255: illegal or missing addressing mode for symbol const_minMatch
asm: assembly of pkg/linux_amd64/github.com/pierrec/lz4/v4/internal/lz4block/decode_amd64.s failed
```

MWE:
```
go_repo(module="github.com/pierrec/lz4/v4", version="v4.1.17")
```

### PR DESCRIPTION
**Pull request by Tatskaari**
Fixes #115

### CODE REVIEW

File: tools/please_go/generate/generate.go [hunk 1]
```diff
@@ -149,6 +149,9 @@ func (g *Generate) generateAll(dir string) error {
 			if info.Name() == "testdata" {
 				return filepath.SkipDir
 			}
+			if path != dir && strings.HasPrefix(info.Name(), "_") {
+				return filepath.SkipDir
+			}
```
Comment (Tatskaari) [inline tools/please_go/generate/generate.go:154]: THis was just another small fix I had laying around to stop us descending into `_blah` dirs. These are almost always some internal nonsense that we don't need to generate BUILD files for.
